import { sql } from "drizzle-orm";
import { integer, text } from "drizzle-orm/sqlite-core";

/**
 * Monetary convention: every money column is stored as an INTEGER in the
 * currency's minor units (e.g. cents). Display formatting (decimal places,
 * separators, symbol) lives in `store_settings`. Coupon `value` is dual:
 * for `percentage` it is a whole percent, for `fixed` it is minor units.
 */

/** Primary key column: random UUID generated by the Workers runtime. */
export const id = () =>
  text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID());

/** created_at + updated_at as unix-second timestamps mapped to `Date`. */
export const timestamps = () => ({
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`),
  updatedAt: integer("updated_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`)
    .$onUpdate(() => new Date()),
});

/** Standalone created_at column for append-only tables. */
export const createdAt = () =>
  integer("created_at", { mode: "timestamp" })
    .notNull()
    .default(sql`(unixepoch())`);

// ---- Shared JSON payload shapes (stored in `text({ mode: "json" })`) ----

export interface BankTransferInfo {
  bankName?: string;
  accountType?: string;
  accountNumber?: string;
  holderName?: string;
  holderDocument?: string;
  email?: string;
  instructions?: string;
}

export interface GuestSnapshot {
  name: string;
  email: string;
  phone?: string;
  idDocument?: string;
  documentType: "receipt" | "invoice";
}

export interface AddressSnapshot {
  label?: string;
  addressLine1: string;
  addressLine2?: string;
  city: string;
  state?: string;
  countryCode: string;
  postalCode?: string;
}

export interface ProductSnapshot {
  productId: string;
  productName: string;
  variantId: string;
  variantName: string;
  sku?: string | null;
  type: "physical" | "digital";
}
